---
abstract: 'A pluggable Markov engine analogous to MegaHAL'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101040'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hailo
no_index:
  directory:
    - inc
    - t
    - xt
    - utils
recommends: {}
requires:
  Any::Moose: 0.11
  Bot::Training: 0
  Bot::Training::MegaHAL: 0
  Bot::Training::StarCraft: 0
  DBD::SQLite: 1.29
  Data::Section: 0.100770
  Dir::Self: 0.10
  File::CountLines: 0.0.2
  File::Slurp: 9999.13
  File::Spec::Functions: 0
  Getopt::Long::Descriptive: 0.083
  IO::Interactive: 0.0.6
  IPC::System::Simple: 1.20
  List::MoreUtils: 0.22
  Moose: 0.94
  MooseX::Getopt: 0.26
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.21
  Mouse: 0.50
  MouseX::Getopt: 0.2601
  MouseX::Types: 0.05
  Term::ProgressBar: 2.00
  Term::ReadLine: 0
  Test::Exception: 0.29
  Test::Expect: 0.30
  Test::More: 0.94
  Test::Output: 0.16
  Test::Script: 1.07
  Test::Script::Run: 0.03
  Test::Synopsis: 0.06
  Time::HiRes: 0
  autodie: 2.08
  namespace::clean: 0.13
  perl: 5.010
resources:
  Ratings: http://cpanratings.perl.org/d/Hailo
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Hailo
  homepage: http://hailo.org
  license: http://dev.perl.org/licenses/
  repository: http://github.com/hailo/hailo
version: 0.41
