---
abstract: 'A pluggable Markov engine analogous to MegaHAL'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Data::Random: 0
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.29
  Test::Exit: 0.03
  Test::More: 0
  Test::Output: 0.16
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hailo
no_index:
  directory:
    - inc
    - t
    - utils
    - xt
recommends:
  CHI: 0.34
  CHI::Driver::BerkeleyDB: 0
  CHI::Driver::File: 0
  CHI::Driver::Memory: 0
  DBD::Pg: 0
  DBD::mysql: 0
requires:
  Class::MOP: 0
  DBD::SQLite: 0
  Data::Section: 0.100270
  Digest::MD4: 0
  File::CountLines: 0
  File::Spec::Functions: 0
  FindBin: 0
  IO::Interactive: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  Module::Pluggable: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Getopt::Dashes: 0
  MooseX::Role::Strict: 0.03
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Pod::Usage: 0
  Template: 0
  Term::ProgressBar: 2.00
  Term::ReadLine::Gnu: 0
  Text::Trim: 0
  autodie: 0
  namespace::clean: 0
  perl: 5.10.0
resources:
  Ratings: http://cpanratings.perl.org/d/Hailo
  bugtracker: http://github.com/hinrik/hailo/issues
  homepage: http://search.cpan.org/dist/Hailo
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/hailo.git
version: 0.09
