---
abstract: 'A pluggable Markov engine analogous to MegaHAL'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Data::Random: 0.05
  ExtUtils::MakeMaker: 6.42
  File::Slurp: 9999.13
  Test::Exception: 0.29
  Test::More: 0.94
  Test::Output: 0.16
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hailo
no_index:
  directory:
    - inc
    - t
    - utils
    - xt
provides:
  Hailo:
    file: lib/Hailo.pm
    version: 0.20
  Hailo::Role::Arguments:
    file: lib/Hailo/Role/Arguments.pm
    version: 0.20
  Hailo::Role::Storage:
    file: lib/Hailo/Role/Storage.pm
    version: 0.20
  Hailo::Role::Tokenizer:
    file: lib/Hailo/Role/Tokenizer.pm
    version: 0.20
  Hailo::Role::UI:
    file: lib/Hailo/Role/UI.pm
    version: 0.20
  Hailo::Storage::DBD:
    file: lib/Hailo/Storage/DBD.pm
    version: 0.20
  Hailo::Storage::DBD::Pg:
    file: lib/Hailo/Storage/DBD/Pg.pm
    version: 0.20
  Hailo::Storage::DBD::SQLite:
    file: lib/Hailo/Storage/DBD/SQLite.pm
    version: 0.20
  Hailo::Storage::DBD::mysql:
    file: lib/Hailo/Storage/DBD/mysql.pm
    version: 0.20
  Hailo::Tokenizer::Chars:
    file: lib/Hailo/Tokenizer/Chars.pm
    version: 0.20
  Hailo::Tokenizer::Words:
    file: lib/Hailo/Tokenizer/Words.pm
    version: 0.20
  Hailo::UI::ReadLine:
    file: lib/Hailo/UI/ReadLine.pm
    version: 0.20
recommends:
  DBD::Pg: 2.16.1
  DBD::mysql: 4.013
requires:
  Any::Moose: 0.11
  DBD::SQLite: 1.29
  Data::Section: 0.100270
  File::CountLines: 0.0.2
  Getopt::Long::Descriptive: 0.083
  IO::Interactive: 0.0.6
  List::MoreUtils: 0.22
  Module::Pluggable: 3.9
  Moose: 0.94
  MooseX::Getopt: 0.26
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.21
  Mouse: 0.50_04
  MouseX::Getopt: 0.2601
  MouseX::Types: 0.05
  Template: 2.22
  Term::ProgressBar: 2.00
  Term::ReadLine::Gnu: 0
  autodie: 2.08
  namespace::clean: 0.13
  perl: 5.10.0
resources:
  Ratings: http://cpanratings.perl.org/d/Hailo
  bugtracker: http://github.com/hinrik/hailo/issues
  homepage: http://search.cpan.org/dist/Hailo
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/hailo.git
version: 0.20
